#!/bin/sh
#
# $FreeBSD: head/net/samba41/files/samba_server.in 379838 2015-02-24 20:44:10Z timur $
#

# PROVIDE: var_samba_dirs
# REQUIRE: clean_var
# BEFORE: samba_server
#
# Samba requires some folders when run, that are not created by
# /etc/rc.d/var. This script creates these folders.

mkdir -p /var/db/samba4/private
mkdir /var/log/samba4
mkdir /var/run/samba4
